/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import DAO.AudioDAO;
import Tabla.Tabla_AudioVO;
import VO.AudioVO;
import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author David
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    AudioDAO dao;
    Tabla_AudioVO t = new Tabla_AudioVO();

    int idaudio = -1;

    public Visual() {
        initComponents();
        t.visualizar_AudioVO(tabla);
        activa(false, false, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void limpiar() {
        txtc.setText("");
        txtn.setText("");
        txtruta.setText("");
        idaudio = -1;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btna = new javax.swing.JButton();
        btne = new javax.swing.JButton();
        btnm = new javax.swing.JButton();
        btnuevo = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtruta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coleccion de Musica");
        setResizable(false);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        btna.setBackground(new java.awt.Color(51, 255, 51));
        btna.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btna.setText("Agregar");
        btna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaActionPerformed(evt);
            }
        });

        btne.setBackground(new java.awt.Color(255, 0, 0));
        btne.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btne.setForeground(new java.awt.Color(255, 255, 255));
        btne.setText("Eliminar");
        btne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneActionPerformed(evt);
            }
        });

        btnm.setBackground(new java.awt.Color(51, 255, 51));
        btnm.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnm.setText("Modificar");
        btnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmActionPerformed(evt);
            }
        });

        btnuevo.setBackground(new java.awt.Color(153, 255, 255));
        btnuevo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnuevo.setText("Nuevo");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });

        btncancelar.setBackground(new java.awt.Color(153, 255, 255));
        btncancelar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnm)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncancelar)
                .addGap(32, 32, 32)
                .addComponent(btne)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnuevo)
                    .addComponent(btna)
                    .addComponent(btnm))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelar)
                    .addComponent(btne))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setForeground(new java.awt.Color(255, 255, 204));

        txtruta.setEditable(false);
        txtruta.setBackground(new java.awt.Color(0, 0, 0));
        txtruta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtruta.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Seleccionar archivo de audio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Titulo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Codigo:");

        txtc.setEditable(false);
        txtc.setBackground(new java.awt.Color(0, 0, 0));
        txtc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtc.setForeground(new java.awt.Color(255, 255, 255));
        txtc.setText("Automatico");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtruta)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtn)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 96, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(177, 177, 177))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser j = new JFileChooser();
        j.setCurrentDirectory(new File("C:\\Users\\david\\Music\\Sonidos Animales"));
        FileNameExtensionFilter fil = new FileNameExtensionFilter("mp3, wav & flac", "mp3", "wav", "flac");
        j.setFileFilter(fil);

        int s = j.showOpenDialog(this);
        if (s == JFileChooser.APPROVE_OPTION) {
            String ruta = j.getSelectedFile().getAbsolutePath();
            String name = j.getSelectedFile().getName();
            txtruta.setText(ruta);
            txtn.setText(name);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaActionPerformed

        String nombre = txtn.getText();
        File ruta = new File(txtruta.getText());

        this.agregar(nombre, ruta);
        t.visualizar_AudioVO(tabla);
        activa(false,false,false,false);
        limpiar();

    }//GEN-LAST:event_btnaActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

        int column = tabla.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tabla.getRowHeight();

        if (row < tabla.getRowCount() && row >= 0 && column < tabla.getColumnCount() && column >= 0) {
            idaudio = (int) tabla.getValueAt(row, 0);
            String name = "" + tabla.getValueAt(row, 1);
            this.txtc.setText(String.valueOf(idaudio));
            activa(false,true,true,true);
            this.txtn.setText(name);
            txtruta.setText("");
            

            Object value = tabla.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("a")) {
                    AudioDAO pd = new AudioDAO();
                    AudioVO vo = new AudioVO();
                    vo = pd.getAudioVOByIdby(idaudio);
                    FileOutputStream fileOuputStream = null;
                    try {
                        fileOuputStream = new FileOutputStream("audio.mp3");
                        fileOuputStream.write(vo.getArchivoaudioby());
                    } catch (Exception ex) {
                        System.out.println(ex.getMessage());
                    } finally {
                        try {
                            fileOuputStream.close();
                            Desktop.getDesktop().open(new File("audio.mp3"));
                        } catch (IOException ex) {
                            Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }

                if (boton.getName().equals("er1")) {
                    JOptionPane.showMessageDialog(null, "Audio no disponible");
                }

                if (boton.getName().equals("d")) {
                    AudioDAO pd = new AudioDAO();
                    AudioVO vo = new AudioVO();
                    vo = pd.getAudioVOByIdby(idaudio);
                    //byte[] bytes = vo.getArchivoaudio();
                    JFileChooser j = new JFileChooser();
                    j.setCurrentDirectory(new File("C:\\Users\\david\\"));
                    j.showSaveDialog(this);
                    File fw = j.getSelectedFile();
                    if (fw != null) {
                        try {
                            FileNameExtensionFilter sf = new FileNameExtensionFilter("mp3", "mp3");
                            j.setFileFilter(sf);
                            OutputStream os = new FileOutputStream(fw.getAbsolutePath() + ".mp3");
                            os.write(vo.getArchivoaudioby());
                            //printContent(file);
                            os.close();
                            System.out.println("Archivo se guardo correctamente");
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }

                }

            }
        }

    }//GEN-LAST:event_tablaMouseClicked

    private void btnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmActionPerformed
        int id = Integer.parseInt(txtc.getText());
        String nombre = txtn.getText();

        File ruta = new File(txtruta.getText().trim());

        if (ruta.length() != 0) {
            this.modificar(nombre, ruta, id);
            t.visualizar_AudioVO(tabla);
            limpiar();
            activa(false,false,false,false);
        } else {
            this.modificar2(nombre, id);
            t.visualizar_AudioVO(tabla);
            limpiar();
            activa(false,false,false,false);
        }
    }//GEN-LAST:event_btnmActionPerformed

    private void btneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneActionPerformed
        int id = Integer.parseInt(txtc.getText());
        int a = JOptionPane.showConfirmDialog(null, "Desea eliminar este Audio", "Mensaje", JOptionPane.OK_CANCEL_OPTION);
        if (a == 0) {
            this.eliminar(id);
            limpiar();
            activa(false,false,false,false);
        }
        t.visualizar_AudioVO(tabla);
    }//GEN-LAST:event_btneActionPerformed

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        activa(true, false, false, true);
        limpiar();
        txtc.setText("Automatico");
    }//GEN-LAST:event_btnuevoActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        activa(false,false,false,false);
        limpiar();
        txtc.setText("Automatico");
    }//GEN-LAST:event_btncancelarActionPerformed

    public void activa(boolean a, boolean b, boolean c, boolean d){
        btna.setEnabled(a);
        btnm.setEnabled(b);
        btne.setEnabled(c);
        btncancelar.setEnabled(d);
        
    }
    
    public void agregar(String nombre, File ruta) {
        AudioVO vo = new AudioVO();
        dao = new AudioDAO();

        vo.setNombreaudio(nombre);

        try {
            byte[] audio = new byte[(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(audio);
            vo.setArchivoaudioby(audio);
        } catch (Exception ex) {
            vo.setArchivoaudioby(null);
        }
        dao.Agregar_AudioVO(vo);
        limpiar();
    }

    public void modificar(String nombre, File ruta, int id) {
        AudioVO vo = new AudioVO();
        dao = new AudioDAO();

        vo.setCodigoaudio(id);
        vo.setNombreaudio(nombre);

        try {
            byte[] audio = new byte[(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(audio);
            vo.setArchivoaudioby(audio);
        } catch (Exception ex) {
            vo.setArchivoaudioby(null);
        }
        dao.Modificar_AudioVO(vo);
    }

    public void modificar2(String nombre, int id) {
        AudioVO vo = new AudioVO();
        AudioDAO dao = new AudioDAO();

        vo.setCodigoaudio(id);
        vo.setNombreaudio(nombre);

        dao.Modificar_AudioVO2(vo);
    }

    public void eliminar(int id) {
        AudioVO vo = new AudioVO();
        dao = new AudioDAO();

        vo.setCodigoaudio(idaudio);

        dao.Eliminar_AudioVO(vo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btna;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btne;
    private javax.swing.JButton btnm;
    private javax.swing.JButton btnuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtc;
    private javax.swing.JTextField txtn;
    private javax.swing.JTextField txtruta;
    // End of variables declaration//GEN-END:variables
}
